### ISSUE TITLE
NO APK FILE

### ISSUE THREAD

**Issue by itissandeep98** [shawnfrost80/MusicLayer#1]
Please provide us with an apk file.

**Comment by shawnfrost80** [comment]
Ruk abhi teri maa chodta hu
PS - Sure will do

**Comment by shawnfrost80** [comment]
> Please provide us with an apk file.

Sure Will do

**Comment by shawnfrost80** [comment]
music_layer.apk is now available to download. Just install it as normal android apk.
Thank you for raising an issue!
